/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels.FormPosao;

import controller.ClientController;
import domain.Menadzer;
import domain.Posao;
import domain.PripadnostZadatkaPoslu;
import domain.Zadatak;
import domain.Zaposleni;
import domain.Zaposlenje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.TableModelZadaci;
import models.TableModelZaposleni;

/**
 *
 * @author milos
 */
public class FormPosao extends javax.swing.JPanel {
    Posao selektovaniPosao;
    ArrayList<Posao> poslovi;
    /**
     * Creates new form FormPosao
     */
    public FormPosao() {
        initComponents();
        popuniComboBoxPoslovi();
        postaviListenerComboBox();
        listenerInit();
        setLastPosao();

        jTextFieldNazivPosla.setEditable(false);
        jTextAreaOpisPosla.setEditable(false);

        jButtonOdustaniOdIzmene.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonNoviPosao = new javax.swing.JButton();
        jTextFieldNazivPosla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOpisPosla = new javax.swing.JTextArea();
        jButtonIzmeniPosao = new javax.swing.JButton();
        jButtonObrisiPosao = new javax.swing.JButton();
        jLabelMenadzer = new javax.swing.JLabel();
        jLabelDatumKreiranja = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableZaposleniNaPoslu = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableZaposleniVanPosla = new javax.swing.JTable();
        jButtonUkloniZaposlenog = new javax.swing.JButton();
        jButtonDodajZaposlenog = new javax.swing.JButton();
        jButtonUkloniZadatak = new javax.swing.JButton();
        jButtonDodajZadatak = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableZadaciNaPoslu = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableZadaciVanPosla = new javax.swing.JTable();
        jComboBoxListaPoslova = new javax.swing.JComboBox();
        jButtonOdustaniOdIzmene = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Posao");

        jLabel2.setText("Posao:");

        jButtonNoviPosao.setText("Novi Posao");
        jButtonNoviPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviPosaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Naziv Posla: ");

        jLabel4.setText("Opis Posla:");

        jTextAreaOpisPosla.setColumns(20);
        jTextAreaOpisPosla.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOpisPosla);

        jButtonIzmeniPosao.setText("Izmeni Posao");
        jButtonIzmeniPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniPosaoActionPerformed(evt);
            }
        });

        jButtonObrisiPosao.setBackground(new java.awt.Color(255, 150, 150));
        jButtonObrisiPosao.setText("Obrisi Posao");
        jButtonObrisiPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiPosaoActionPerformed(evt);
            }
        });

        jLabelMenadzer.setText("Menadzer");

        jLabelDatumKreiranja.setText("Datum Kreiranja");

        jLabel6.setText("Datum Kreiranja:");

        jLabel5.setText("Menadzer: ");

        jLabel7.setText("Zaposleni:");

        jTableZaposleniNaPoslu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableZaposleniNaPoslu);

        jTableZaposleniVanPosla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableZaposleniVanPosla);

        jButtonUkloniZaposlenog.setText("Ukloni Zaposlenog");
        jButtonUkloniZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUkloniZaposlenogActionPerformed(evt);
            }
        });

        jButtonDodajZaposlenog.setText("Dodaj Zaposlenog");
        jButtonDodajZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajZaposlenogActionPerformed(evt);
            }
        });

        jButtonUkloniZadatak.setText("Ukloni Zadatak");
        jButtonUkloniZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUkloniZadatakActionPerformed(evt);
            }
        });

        jButtonDodajZadatak.setText("Dodaj Zadatak");
        jButtonDodajZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajZadatakActionPerformed(evt);
            }
        });

        jLabel8.setText("Zadaci:");

        jTableZadaciNaPoslu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableZadaciNaPoslu);

        jTableZadaciVanPosla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableZadaciVanPosla);

        jComboBoxListaPoslova.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonOdustaniOdIzmene.setText("Odustani");
        jButtonOdustaniOdIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniOdIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUkloniZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDodajZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelDatumKreiranja)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonObrisiPosao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelMenadzer)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonOdustaniOdIzmene)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonIzmeniPosao))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonNoviPosao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNazivPosla, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxListaPoslova, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonUkloniZadatak, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonDodajZadatak, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonNoviPosao)
                    .addComponent(jComboBoxListaPoslova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNazivPosla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmeniPosao)
                    .addComponent(jLabelMenadzer)
                    .addComponent(jLabel5)
                    .addComponent(jButtonOdustaniOdIzmene))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonObrisiPosao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDatumKreiranja)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUkloniZaposlenog)
                    .addComponent(jButtonDodajZaposlenog))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUkloniZadatak)
                    .addComponent(jButtonDodajZadatak))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNoviPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviPosaoActionPerformed
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent instanceof java.awt.Frame) {
            FormNoviPosao forma = new FormNoviPosao((java.awt.Frame) parent, true, this);
            forma.setVisible(true);
        } else {
            System.out.println("Parent nije JFrame ili Frame");
        }
    }//GEN-LAST:event_jButtonNoviPosaoActionPerformed

    private void jButtonObrisiPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiPosaoActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete ovaj posao?", 
                                                 "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (selektovaniPosao == null) {
            JOptionPane.showMessageDialog(this, "Nije selektovan posao!");
            return;
        }

        // Prvo brisanje svih pripadnosti zadacima
        try {
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            for (PripadnostZadatkaPoslu prip : svePripadnosti) {
                if (prip.getPosaoID().equals(selektovaniPosao.getPosaoID())) {
                    ClientController.getInstance().deletePripadnostZP(prip);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri brisanju pripadnosti zadacima: " + ex.getMessage());
            return; // Prekidamo izvršavanje ukoliko nastane greška
        }

        // Nakon toga brisanje svih zaposlenja vezanih za taj posao
        try {
            ArrayList<Zaposlenje> svaZaposljenja = ClientController.getInstance().getAllZaposlenja();
            for (Zaposlenje z : svaZaposljenja) {
                if (z.getPosaoID().equals(selektovaniPosao.getPosaoID())) {
                    ClientController.getInstance().deleteZaposlenje(z);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri brisanju zaposlenja: " + ex.getMessage());
            return;
        }

        // Na kraju, brisanje samog posla
        try {
            ClientController.getInstance().deletePosao(selektovaniPosao);
            JOptionPane.showMessageDialog(this, "Posao i sve povezane veze su uspešno obrisani.");
            popuniComboBoxPoslovi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom brisanja posla: " + ex.getMessage());
        }

        setLastPosao();
    }//GEN-LAST:event_jButtonObrisiPosaoActionPerformed

    private void jButtonIzmeniPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniPosaoActionPerformed
        // Ako trenutno nije u režimu izmene (tekst je "Izmeni Posao")
        if(jButtonIzmeniPosao.getText().equals("Izmeni Posao")){
            // Omogućavamo uređivanje
            jTextFieldNazivPosla.setEditable(true);
            jTextAreaOpisPosla.setEditable(true);
            // Menjamo tekst na dugmetu
            jButtonIzmeniPosao.setText("Sacuvaj");
            // Prikazujemo dugme za odustajanje
            jButtonOdustaniOdIzmene.setVisible(true);
        } else {
            // U režimu smo "Sacuvaj", dakle pokupimo izmene
            String noviNaziv = jTextFieldNazivPosla.getText().trim();
            String noviOpis = jTextAreaOpisPosla.getText().trim();
            
            // Možete dodati validaciju (npr. ne smeju biti prazni)
            if(noviNaziv.isEmpty() || noviOpis.isEmpty()){
                JOptionPane.showMessageDialog(this, "Naziv i opis ne mogu biti prazni!");
                return;
            }
            
            // Preuzmemo trenutni posao iz combo box-a
            if(selektovaniPosao == null){
                JOptionPane.showMessageDialog(this, "Nije selektovan posao!");
                return;
            }
            
            try {
                poslovi = ClientController.getInstance().getAllPoslovi();
                for(Posao p : poslovi){
                    if(noviNaziv.equals(p.getNazivPosla()) && !noviNaziv.equals(selektovaniPosao.getNazivPosla())){
                        JOptionPane.showMessageDialog(this, "Posao sa ovim nazivom vec postoji!");
                        return;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(FormNoviPosao.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // Postavljamo nove vrednosti
            selektovaniPosao.setNazivPosla(noviNaziv);
            selektovaniPosao.setOpisPosla(noviOpis);
            
            try {
                ClientController.getInstance().updatePosao(selektovaniPosao);
                JOptionPane.showMessageDialog(this, "Posao je uspešno izmenjen!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greška prilikom izmene posla: " + ex.getMessage());
                Logger.getLogger(FormPosao.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // Vraćamo polja u režim neizmenjivosti
            jTextFieldNazivPosla.setEditable(false);
            jTextAreaOpisPosla.setEditable(false);
            // Vraćamo tekst dugmeta na početni
            jButtonIzmeniPosao.setText("Izmeni Posao");
            // Sakrivamo dugme odustani
            jButtonOdustaniOdIzmene.setVisible(false);
            
            // Ažuriramo prikaz (možete osvežiti combo box ili samo prikaz podataka)
            popuniComboBoxPoslovi();
            refreshAll();
        }
    }//GEN-LAST:event_jButtonIzmeniPosaoActionPerformed

    private void jButtonOdustaniOdIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniOdIzmeneActionPerformed
        // Vraćamo originalne vrednosti iz selektovanog posla
        prikaziPodatkeOPoslu();
        // Postavljamo polja u režim neizmenjivosti
        jTextFieldNazivPosla.setEditable(false);
        jTextAreaOpisPosla.setEditable(false);
        // Vraćamo dugme "Izmeni Posao" na početni tekst
        jButtonIzmeniPosao.setText("Izmeni Posao");
        // Sakrivamo dugme odustani
        jButtonOdustaniOdIzmene.setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniOdIzmeneActionPerformed

    private void jButtonUkloniZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUkloniZaposlenogActionPerformed
        if(selektovaniPosao == null){
            JOptionPane.showMessageDialog(this, "Nije selektovan posaO!");
            return;
        }

        int red = jTableZaposleniNaPoslu.getSelectedRow();
        if(red < 0){
            JOptionPane.showMessageDialog(this, "Nije selektovan zaposleni za uklanjanje.");
            return;
        }

        TableModelZaposleni modelNaPoslu = (TableModelZaposleni) jTableZaposleniNaPoslu.getModel();
        domain.Zaposleni selektovaniZaposleni = modelNaPoslu.getSelectedZaposleni(red);

        try {
            // Učitaj sva zaposlenja i pronađi ono koje odgovara selektovanom poslu i zaposlenom.
            ArrayList<domain.Zaposlenje> svaZaposljenja = ClientController.getInstance().getAllZaposlenja();
            domain.Zaposlenje zaposlenjeZaBrisanje = null;
            for(domain.Zaposlenje z : svaZaposljenja){
                if(z.getPosaoID().equals(selektovaniPosao.getPosaoID()) &&
                   z.getZaposleniID().equals(selektovaniZaposleni.getZaposleniID())){
                    zaposlenjeZaBrisanje = z;
                    break;
                }
            }
            if(zaposlenjeZaBrisanje != null){
                ClientController.getInstance().deleteZaposlenje(zaposlenjeZaBrisanje);
                JOptionPane.showMessageDialog(this, "Zaposleni je uklonjen sa posla.");
                popuniTabeleZaposleni();
            } else {
                JOptionPane.showMessageDialog(this, "Nije pronađeno zaposlenje za ovog zaposlenog.");
            }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri uklanjanju zaposlenog: " + ex.getMessage());
        }
        refreshAll();
    }//GEN-LAST:event_jButtonUkloniZaposlenogActionPerformed

    private void jButtonDodajZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajZaposlenogActionPerformed
        if(selektovaniPosao == null){
            JOptionPane.showMessageDialog(this, "Nije selektovan posla!");
            return;
        }

        int red = jTableZaposleniVanPosla.getSelectedRow();
        if(red < 0){
            JOptionPane.showMessageDialog(this, "Nije selektovan zaposleni za dodavanje.");
            return;
        }

        TableModelZaposleni modelVanPosla = (TableModelZaposleni) jTableZaposleniVanPosla.getModel();
        Zaposleni selektovaniZaposleni = modelVanPosla.getSelectedZaposleni(red);

        try {
            // Provera da li je zaposlenje već kreirano za ovaj par (posao, zaposleni)
            ArrayList<Zaposlenje> svaZaposljenja = ClientController.getInstance().getAllZaposlenja();
            for(Zaposlenje z : svaZaposljenja){
                if(z.getPosaoID().equals(selektovaniPosao.getPosaoID()) &&
                   z.getZaposleniID().equals(selektovaniZaposleni.getZaposleniID())){
                    JOptionPane.showMessageDialog(this, "Zaposleni je već povezan sa ovim poslom.");
                    return;
                }
            }

            // Kreiraj novo zaposlenje s trenutnim datumom kao datum početka
            Zaposlenje novoZaposlenje = new domain.Zaposlenje();
            novoZaposlenje.setPosaoID(selektovaniPosao.getPosaoID());
            novoZaposlenje.setZaposleniID(selektovaniZaposleni.getZaposleniID());
            novoZaposlenje.setDatumPocetkaZap(new java.util.Date());
            // Datum završetka se postavlja na null ili po potrebi
            novoZaposlenje.setDatumZavrsetkaZap(null);

            ClientController.getInstance().addZaposlenje(novoZaposlenje);
            JOptionPane.showMessageDialog(this, "Zaposleni je dodan na posao.");
            popuniTabeleZaposleni();
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri dodavanju zaposlenog: " + ex.getMessage());
        }
        refreshAll();
    }//GEN-LAST:event_jButtonDodajZaposlenogActionPerformed

    private void jButtonDodajZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajZadatakActionPerformed
        if(selektovaniPosao == null){
            JOptionPane.showMessageDialog(this, "Nije selektovan posao!");
            return;
        }

        int red = jTableZadaciVanPosla.getSelectedRow();
        if(red < 0){
            JOptionPane.showMessageDialog(this, "Nije selektovan zadatak za dodavanje.");
            return;
        }

        TableModelZadaci modelVanPosla = (TableModelZadaci) jTableZadaciVanPosla.getModel();
        Zadatak selektovaniZadatak = modelVanPosla.getSelectedZadatak(red);

        try {
            // Provera da li veza (pripadnost) već postoji
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (p.getPosaoID().equals(selektovaniPosao.getPosaoID()) &&
                    p.getZadatakID().equals(selektovaniZadatak.getZadatakID())) {
                    JOptionPane.showMessageDialog(this, "Zadatak je već povezan sa ovim poslom.");
                    return;
                }
            }

            // Kreiranje nove pripadnosti: postavljamo datum početka na trenutni, a datum završetka možemo postaviti na null
            PripadnostZadatkaPoslu novaPripadnost = new PripadnostZadatkaPoslu();
            novaPripadnost.setPosaoID(selektovaniPosao.getPosaoID());
            novaPripadnost.setZadatakID(selektovaniZadatak.getZadatakID());
            novaPripadnost.setDatumPocetkaPrip(new java.util.Date());
            novaPripadnost.setDatumZavrsetkaPrip(null);

            ClientController.getInstance().addPripadnostZP(novaPripadnost);
            JOptionPane.showMessageDialog(this, "Zadatak je dodat na posao.");
            popuniTabeleZadaci();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri dodavanju zadatka: " + ex.getMessage());
        }
        refreshAll();
    }//GEN-LAST:event_jButtonDodajZadatakActionPerformed

    private void jButtonUkloniZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUkloniZadatakActionPerformed
        if(selektovaniPosao == null){
            JOptionPane.showMessageDialog(this, "Nije selektovan posao!");
            return;
        }

        int red = jTableZadaciNaPoslu.getSelectedRow();
        if(red < 0){
            JOptionPane.showMessageDialog(this, "Nije selektovan zadatak za uklanjanje.");
            return;
        }

        TableModelZadaci modelNaPoslu = (TableModelZadaci) jTableZadaciNaPoslu.getModel();
        Zadatak selektovaniZadatak = modelNaPoslu.getSelectedZadatak(red);

        try {
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            PripadnostZadatkaPoslu pripZaBrisanje = null;
            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (p.getPosaoID().equals(selektovaniPosao.getPosaoID()) &&
                    p.getZadatakID().equals(selektovaniZadatak.getZadatakID())) {
                    pripZaBrisanje = p;
                    break;
                }
            }
            if(pripZaBrisanje != null){
                ClientController.getInstance().deletePripadnostZP(pripZaBrisanje);
                JOptionPane.showMessageDialog(this, "Zadatak je uklonjen sa posla.");
                popuniTabeleZadaci();
            } else {
                JOptionPane.showMessageDialog(this, "Nije pronađen zadatak za uklanjanje.");
            }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri uklanjanju zadatka: " + ex.getMessage());
        }
        refreshAll();
    }//GEN-LAST:event_jButtonUkloniZadatakActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajZadatak;
    private javax.swing.JButton jButtonDodajZaposlenog;
    private javax.swing.JButton jButtonIzmeniPosao;
    private javax.swing.JButton jButtonNoviPosao;
    private javax.swing.JButton jButtonObrisiPosao;
    private javax.swing.JButton jButtonOdustaniOdIzmene;
    private javax.swing.JButton jButtonUkloniZadatak;
    private javax.swing.JButton jButtonUkloniZaposlenog;
    private javax.swing.JComboBox jComboBoxListaPoslova;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDatumKreiranja;
    private javax.swing.JLabel jLabelMenadzer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableZadaciNaPoslu;
    private javax.swing.JTable jTableZadaciVanPosla;
    private javax.swing.JTable jTableZaposleniNaPoslu;
    private javax.swing.JTable jTableZaposleniVanPosla;
    private javax.swing.JTextArea jTextAreaOpisPosla;
    private javax.swing.JTextField jTextFieldNazivPosla;
    // End of variables declaration//GEN-END:variables

    private void refreshPoslovi(){
        try {
            poslovi = ClientController.getInstance().getAllPoslovi();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju poslova: " + ex.getMessage());
        }
    }
    
    public void popuniComboBoxPoslovi() {
        refreshPoslovi();
        DefaultComboBoxModel<Posao> model = new DefaultComboBoxModel<>();
        for (Posao p : poslovi) {
            model.addElement(p);
        }
        jComboBoxListaPoslova.setModel(model);
    }

    private void postaviListenerComboBox() {
        jComboBoxListaPoslova.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selektovaniPosao = (Posao) jComboBoxListaPoslova.getSelectedItem();
                prikaziPodatkeOPoslu();
            }
        });
    }
    
    public void prikaziPodatkeOPoslu() {
        if (selektovaniPosao != null) {
            jComboBoxListaPoslova.setSelectedItem(selektovaniPosao);
            jTextFieldNazivPosla.setText(selektovaniPosao.getNazivPosla());
            jTextAreaOpisPosla.setText(selektovaniPosao.getOpisPosla());
            Menadzer m = selektovaniPosao.getMenadzer();
            if (m != null) {
                jLabelMenadzer.setText(m.getIme() + " " + m.getPrezime());
            } else {
                jLabelMenadzer.setText("N/A");
            }
            jLabelDatumKreiranja.setText(selektovaniPosao.getDatumKreiranjaPosla().toString());
        }
        popuniTabeleZaposleni();
        popuniTabeleZadaci(); 
    }
    
    private void popuniTabeleZaposleni(){
        try {
            if(selektovaniPosao == null) {
                return;
            }

            // Učitaj sve zaposlene i zaposlenja
            ArrayList<Zaposleni> sviZaposleni = ClientController.getInstance().getAllZaposleni();
            // Pretpostavljamo da metoda getAllZaposlenje() vraća ArrayList<domain.Zaposlenje>
            ArrayList<Zaposlenje> svaZaposljenja = ClientController.getInstance().getAllZaposlenja();

            // Filtriraj zaposlenja koja se odnose na selektovani posla
            ArrayList<Zaposleni> zaposleniNaPoslu = new ArrayList<>();
            for(domain.Zaposlenje z : svaZaposljenja) {
                // Pretpostavljamo da Posao ima metodu getPosaoID() – prilagodi prema tvojoj implementaciji
                if(z.getPosaoID().equals(selektovaniPosao.getPosaoID())){
                    // Na osnovu ID-ja zaposlenog, pronađi odgovarajućeg zaposlenog
                    for(Zaposleni zap : sviZaposleni) {
                        if(zap.getZaposleniID().equals(z.getZaposleniID())){
                            zaposleniNaPoslu.add(zap);
                            break;
                        }
                    }
                }
            }

            // Kreiraj listu zaposlenih koji nisu na poslu: sviZaposleni - zaposleniNaPoslu
            ArrayList<Zaposleni> zaposleniVanPosla = new ArrayList<>(sviZaposleni);
            // Ako equals nije pravilno implementiran, možeš koristiti ručno uklanjanje:
            for(Zaposleni zapNaPoslu : zaposleniNaPoslu) {
                for (int i = 0; i < zaposleniVanPosla.size(); i++) {
                    Zaposleni zapVan = zaposleniVanPosla.get(i);
                    if(zapVan.getZaposleniID().equals(zapNaPoslu.getZaposleniID())){
                        zaposleniVanPosla.remove(i);
                        break;
                    }
                }
            }

            // Postavi modele tabela koristeći novi konstruktor
            TableModelZaposleni modelNaPoslu = new TableModelZaposleni(zaposleniNaPoslu);
            TableModelZaposleni modelVanPosla = new TableModelZaposleni(zaposleniVanPosla);
            jTableZaposleniNaPoslu.setModel(modelNaPoslu);
            jTableZaposleniVanPosla.setModel(modelVanPosla);
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju zaposlenih: " + ex.getMessage());
        }
    }
  
    private void popuniTabeleZadaci() {
        try {
            if (selektovaniPosao == null) {
                return;
            }

            // Učitavanje svih zadataka i pripadnosti
            ArrayList<Zadatak> sviZadaci = ClientController.getInstance().getAllZadaci();
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();

            // Filter zadataka koji su vezani za izabrani posao
            ArrayList<Zadatak> zadaciNaPoslu = new ArrayList<>();
            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (p.getPosaoID().equals(selektovaniPosao.getPosaoID())) {
                    for (Zadatak z : sviZadaci) {
                        if (z.getZadatakID().equals(p.getZadatakID())) {
                            zadaciNaPoslu.add(z);
                            break;
                        }
                    }
                }
            }

            // Zadaci koji nisu dodeljeni tom poslu
            ArrayList<Zadatak> zadaciVanPosla = new ArrayList<>(sviZadaci);
            for (Zadatak z : zadaciNaPoslu) {
                zadaciVanPosla.removeIf(zv -> zv.getZadatakID().equals(z.getZadatakID()));
            }

            // Postavljanje modela tabela
            TableModelZadaci modelNaPoslu = new TableModelZadaci(zadaciNaPoslu);
            TableModelZadaci modelVanPosla = new TableModelZadaci(zadaciVanPosla);
            jTableZadaciNaPoslu.setModel(modelNaPoslu);
            jTableZadaciVanPosla.setModel(modelVanPosla);

            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju zadataka: " + ex.getMessage());
        }
    }
    
    private void listenerInit() {
        // Dodavanje listener-a za dvostruki klik na tabelu zadataka na poslu
        jTableZadaciNaPoslu.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTableZadaciNaPoslu.getSelectedRow();
                    TableModelZadaci modelNaPoslu = (TableModelZadaci) jTableZadaciNaPoslu.getModel();
                    if (red != -1 && red < modelNaPoslu.getRowCount()) {
                        Zadatak selektovaniZadatak = modelNaPoslu.getSelectedZadatak(red);
                        if (selektovaniZadatak != null) {
                            otvoriFormuZadatak(selektovaniZadatak);
                        }
                    }
                }
            }
        });

        // Listener za dvostruki klik na zadatke van posla
        jTableZadaciVanPosla.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTableZadaciVanPosla.getSelectedRow();
                    TableModelZadaci modelVanPosla = (TableModelZadaci) jTableZadaciVanPosla.getModel();
                    if (red != -1 && red < modelVanPosla.getRowCount()) {
                        Zadatak selektovaniZadatak = modelVanPosla.getSelectedZadatak(red);
                        if (selektovaniZadatak != null) {
                            otvoriFormuZadatak(selektovaniZadatak);
                        }
                    }
                }
            }
        });
            
        // Dodavanje MouseListener-a za tabelu "zaposleni na poslu"
        jTableZaposleniNaPoslu.addMouseListener(new java.awt.event.MouseAdapter(){
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTableZaposleniNaPoslu.getSelectedRow();
                    TableModelZaposleni model = (TableModelZaposleni) jTableZaposleniNaPoslu.getModel();
                    if (red >= 0 && red < model.getRowCount()) {
                        Zaposleni selektovaniZaposleni = model.getSelectedZaposleni(red);
                        if (selektovaniZaposleni != null) {
                            otvoriFormuZaposleni(selektovaniZaposleni);
                        }
                    }
                }
            }
        });

        // I slično za tabelu "zaposleni van posla"
        jTableZaposleniVanPosla.addMouseListener(new java.awt.event.MouseAdapter(){
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if(evt.getClickCount() == 2) { // Dvostruki klik
                    int red = jTableZaposleniVanPosla.getSelectedRow();
                    TableModelZaposleni modelVanPosla = (TableModelZaposleni) jTableZaposleniVanPosla.getModel();
                    if(red >= 0 && red < modelVanPosla.getRowCount()) {
                        Zaposleni selektovaniZaposleni = modelVanPosla.getSelectedZaposleni(red);
                        if (selektovaniZaposleni != null) {
                            otvoriFormuZaposleni(selektovaniZaposleni);
                        }
                    }
                }
            }
        });
    }
    
    private void otvoriFormuZaposleni(Zaposleni zap) {
        // Dobavi roditeljsku formu (MainFormMenadzer) preko SwingUtilities, a zatim pozovi setter na formi Zaposleni:
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if(win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            // Postavi selektovanog zaposlenog u FormZaposleni i prebaci karticu na Zaposleni panel
            mainForm.getFormZaposleni().setSelectedZaposleni(zap);
            mainForm.navigateToPanel("Zaposleni");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }
    
    private void otvoriFormuZadatak(Zadatak zadatak) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            // Pretpostavlja se da MainFormMenadzer ima metodu getFormZadatak() sa setter-om
            mainForm.getFormZadatak().setSelectedZadatak(zadatak);
            mainForm.navigateToPanel("Zadatak");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }
    
    public void setSelectedPosao(Posao p){
        selektovaniPosao = p;
        prikaziPodatkeOPoslu(); 
    }
    
    public void setLastPosao() {
        if (poslovi != null && !poslovi.isEmpty()) {
            Posao poslednji = poslovi.get(poslovi.size() - 1);
            setSelectedPosao(poslednji);
            refreshAll();
        }
    }
    
    private void refreshAll() {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            mainForm.refreshAllMain();
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }

    public Posao getSelektovaniPosao() {
        return selektovaniPosao;
    }

    public ArrayList<Posao> getPoslovi() {
        return poslovi;
    }

}
