/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package panels.FormPosao;

import controller.ClientController;
import domain.Menadzer;
import domain.Posao;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author milos
 */
public class FormNoviPosao extends javax.swing.JDialog {
    private FormPosao parentForm;
    /**
     * Creates new form FormNoviPosao
     */
    public FormNoviPosao(java.awt.Frame parent, boolean modal, FormPosao parentForm) {
        super(parent, modal);
        initComponents();
        this.parentForm = parentForm;
        // Opcionalno: centriranje dijaloga
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOpisPosla = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNazivPosla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextAreaOpisPosla.setColumns(20);
        jTextAreaOpisPosla.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOpisPosla);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Novi Posao");

        jLabel3.setText("Naziv Posla: ");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel10.setText("Opis Posla: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jTextFieldNazivPosla, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOdustani))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNazivPosla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSacuvaj)
                    .addComponent(jButtonOdustani))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        String naziv = jTextFieldNazivPosla.getText().trim();
        String opis = jTextAreaOpisPosla.getText().trim();

        if(naziv.isEmpty() || opis.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate uneti naziv i opis posla!");
            return;
        }
        
        try {
            ArrayList <Posao> poslovi = ClientController.getInstance().getAllPoslovi();
            for(Posao p : poslovi){
                if(naziv.equals(p.getNazivPosla())){
                    JOptionPane.showMessageDialog(this, "Posao sa ovim nazivom vec postoji!");
                    return;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(FormNoviPosao.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            // Kreiranje novog posla – id je null, datum je trenutni, a menadžer se uzima iz ulogovanog korisnika
            Menadzer trenutniMenadzer = (Menadzer) ClientController.getInstance().getUlogovani();
            Posao noviPosao = new Posao(null, naziv, opis, new Date(), trenutniMenadzer);

            // Slanje zahteva ka serveru za kreiranje posla
            noviPosao = ClientController.getInstance().addPosao(noviPosao);

            // Ako je kreiranje uspešno, dodajemo posao u FormPosao
            if (parentForm != null) {
                parentForm.popuniComboBoxPoslovi();
                parentForm.setLastPosao();
            }
            
            JOptionPane.showMessageDialog(this, "Posao je uspešno kreiran!");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja posla: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOpisPosla;
    private javax.swing.JTextField jTextFieldNazivPosla;
    // End of variables declaration//GEN-END:variables
}
