/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels.FormZaposleni;

import controller.ClientController;
import domain.Menadzer;
import domain.Posao;
import domain.PripadnostZadatkaPoslu;
import domain.Zadatak;
import domain.Zaposleni;
import domain.Zaposlenje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.TableModelPoslovi;

/**
 *
 * @author milos
 */
public class FormZaposleni extends javax.swing.JPanel {

    Zaposleni selektovaniZaposleni;
    ArrayList<Zaposleni> zaposleni;
    
    /**
     * Creates new form FormZaposleni
     */
    public FormZaposleni() {
        initComponents();
        popuniComboBoxZaposleni();
        postaviListenerComboBoxZaposleni();
        listenerInit();
        setLastZaposleni();
        
        // Početno stanje – polja su neizmenjiva
        omoguciIzmenu(false);
        // Dugme za odustajanje sakriveno
        jButtonOdustaniOdIzmene.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListaZaposlenih = new javax.swing.JComboBox();
        jButtonNoviZaposleni = new javax.swing.JButton();
        jTextFieldImeZaposlenog = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonIzmeniZaposlenog = new javax.swing.JButton();
        jButtonObrisiZaposlenog = new javax.swing.JButton();
        jLabelMenadzer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePosloviPovezani = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePosloviNepovezani = new javax.swing.JTable();
        jButtonUkloniPosao = new javax.swing.JButton();
        jButtonDodajPosao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableZadaciZaposlenog = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPrezimeZaposlenog = new javax.swing.JTextField();
        jTextFieldTelefonZaposlenog = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEmailZaposlenog = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordLozinkaZaposlenog = new javax.swing.JPasswordField();
        jButtonOdustaniOdIzmene = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zaposleni");

        jLabel2.setText("Zaposleni:");

        jComboBoxListaZaposlenih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonNoviZaposleni.setText("Novi Zaposleni");
        jButtonNoviZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviZaposleniActionPerformed(evt);
            }
        });

        jLabel3.setText("Ime:");

        jButtonIzmeniZaposlenog.setText("Izmeni Zaposlenog");
        jButtonIzmeniZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniZaposlenogActionPerformed(evt);
            }
        });

        jButtonObrisiZaposlenog.setBackground(new java.awt.Color(255, 150, 150));
        jButtonObrisiZaposlenog.setText("Obrisi Zaposlenog");
        jButtonObrisiZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiZaposlenogActionPerformed(evt);
            }
        });

        jLabelMenadzer.setText("Menadzer");

        jLabel5.setText("Menadzer: ");

        jLabel7.setText("Poslovi:");

        jTablePosloviPovezani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePosloviPovezani);

        jTablePosloviNepovezani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTablePosloviNepovezani);

        jButtonUkloniPosao.setText("Ukloni Posao");
        jButtonUkloniPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUkloniPosaoActionPerformed(evt);
            }
        });

        jButtonDodajPosao.setText("Dodaj Posao");
        jButtonDodajPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajPosaoActionPerformed(evt);
            }
        });

        jLabel8.setText("Zadaci: ");

        jTableZadaciZaposlenog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableZadaciZaposlenog);

        jLabel10.setText("Prezime: ");

        jLabel11.setText("Telefon: ");

        jLabel12.setText("Email: ");

        jLabel13.setText("Lozinka: ");

        jButtonOdustaniOdIzmene.setText("Odustani");
        jButtonOdustaniOdIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniOdIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUkloniPosao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDodajPosao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(61, 61, 61)
                                    .addComponent(jTextFieldTelefonZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPrezimeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2))
                                            .addGap(53, 53, 53))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBoxListaZaposlenih, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonNoviZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextFieldImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabelMenadzer)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonOdustaniOdIzmene)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonObrisiZaposlenog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonIzmeniZaposlenog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldEmailZaposlenog, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                        .addComponent(jPasswordLozinkaZaposlenog)))))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxListaZaposlenih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonNoviZaposleni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrezimeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefonZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmailZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jPasswordLozinkaZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelMenadzer)
                    .addComponent(jButtonIzmeniZaposlenog)
                    .addComponent(jButtonOdustaniOdIzmene))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonObrisiZaposlenog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUkloniPosao)
                    .addComponent(jButtonDodajPosao))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNoviZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviZaposleniActionPerformed
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent instanceof java.awt.Frame) {
            FormNoviZaposleni forma = new FormNoviZaposleni((java.awt.Frame) parent, true, this);
            forma.setVisible(true);
        } else {
            System.out.println("Parent nije JFrame ili Frame");
        }
    }//GEN-LAST:event_jButtonNoviZaposleniActionPerformed

    private void jButtonIzmeniZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniZaposlenogActionPerformed
        // Ako trenutno nismo u režimu izmene
        if(jButtonIzmeniZaposlenog.getText().equals("Izmeni zaposlenog")){
            omoguciIzmenu(true);
            jButtonIzmeniZaposlenog.setText("Sačuvaj");
            jButtonOdustaniOdIzmene.setVisible(true);
        } else {
            // U režimu "Sačuvaj", pokupimo izmene
            String ime = jTextFieldImeZaposlenog.getText().trim();
            String prezime = jTextFieldPrezimeZaposlenog.getText().trim();
            String telefon = jTextFieldTelefonZaposlenog.getText().trim();
            String email = jTextFieldEmailZaposlenog.getText().trim();
            String lozinka = new String(jPasswordLozinkaZaposlenog.getPassword()).trim();

            // Validacija unosa – sva polja moraju biti popunjena
            if(ime.isEmpty() || prezime.isEmpty() || telefon.isEmpty() || email.isEmpty() || lozinka.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
                return;
            }
            
            // Preuzimanje selektovanog zaposlenog
            if(selektovaniZaposleni == null){
                JOptionPane.showMessageDialog(this, "Nije selektovan zaposleni!");
                return;
            }
            
            // Provera jedinstvenosti email-a
            try {
                zaposleni = ClientController.getInstance().getAllZaposleni();
                for(Zaposleni z : zaposleni){
                    if(email.equals(z.getEmail()) && !email.equals(selektovaniZaposleni.getEmail())){
                        JOptionPane.showMessageDialog(this, "Zaposleni sa ovim email-om već postoji!");
                        return;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(FormZaposleni.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // Postavljanje novih vrednosti
            selektovaniZaposleni.setIme(ime);
            selektovaniZaposleni.setPrezime(prezime);
            selektovaniZaposleni.setTelefon(telefon);
            selektovaniZaposleni.setEmail(email);
            selektovaniZaposleni.setLozinka(lozinka);
            
            // Pokušaj slanja izmenjenog zaposlenog serveru
            try {
                ClientController.getInstance().updateZaposleni(selektovaniZaposleni);
                JOptionPane.showMessageDialog(this, "Zaposleni je uspešno izmenjen!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greška prilikom izmene zaposlenog: " + ex.getMessage());
                Logger.getLogger(FormZaposleni.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // Vraćamo formu u režim pregleda
            omoguciIzmenu(false);
            jButtonIzmeniZaposlenog.setText("Izmeni zaposlenog");
            jButtonOdustaniOdIzmene.setVisible(false);
            popuniComboBoxZaposleni();
            refreshAll();
        }
    }//GEN-LAST:event_jButtonIzmeniZaposlenogActionPerformed

    private void jButtonOdustaniOdIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniOdIzmeneActionPerformed
        prikaziPodatkeOZaposlenom();
        omoguciIzmenu(false);
        jButtonIzmeniZaposlenog.setText("Izmeni zaposlenog");
        jButtonOdustaniOdIzmene.setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniOdIzmeneActionPerformed

    private void jButtonObrisiZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiZaposlenogActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete ovog zaposlenog?", 
                                                    "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if(result == JOptionPane.NO_OPTION){
            return;
        }
        
        if(selektovaniZaposleni == null) {
            JOptionPane.showMessageDialog(this, "Nije selektovan zaposleni!");
            return;
        }
        
        // Brisanje svih zaposlenja vezanih za taj posao
        try {
            ArrayList<Zaposlenje> svaZaposljenja = ClientController.getInstance().getAllZaposlenja();
            for (Zaposlenje z : svaZaposljenja) {
                if (z.getZaposleniID().equals(selektovaniZaposleni.getZaposleniID())) {
                    ClientController.getInstance().deleteZaposlenje(z);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri brisanju zaposlenja: " + ex.getMessage());
            return;
        }
        
        try {
            ClientController.getInstance().deleteZaposleni(selektovaniZaposleni);
            popuniComboBoxZaposleni();
            JOptionPane.showMessageDialog(this, "Zaposleni je uspešno obrisan!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom brisanja zaposlenog: " + ex.getMessage());
            Logger.getLogger(FormZaposleni.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setLastZaposleni();
    }//GEN-LAST:event_jButtonObrisiZaposlenogActionPerformed

    private void jButtonUkloniPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUkloniPosaoActionPerformed
        if (selektovaniZaposleni == null) {
            JOptionPane.showMessageDialog(this, "Nije selektovan zaposleni!");
            return;
        }

        int red = jTablePosloviPovezani.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Nije selektovan posao za uklanjanje.");
            return;
        }

        TableModelPoslovi modelPoslovi = (TableModelPoslovi) jTablePosloviPovezani.getModel();
        Posao selektovaniPosao = modelPoslovi.getSelectedPosao(red);

        try {
            ArrayList<Zaposlenje> svaZaposlenja = ClientController.getInstance().getAllZaposlenja();
            Zaposlenje zaposleniZaBrisanje = null;

            for (Zaposlenje z : svaZaposlenja) {
                if (z.getZaposleniID().equals(selektovaniZaposleni.getZaposleniID()) &&
                    z.getPosaoID().equals(selektovaniPosao.getPosaoID())) {
                    zaposleniZaBrisanje = z;
                    break;
                }
            }

            if (zaposleniZaBrisanje != null) {
                ClientController.getInstance().deleteZaposlenje(zaposleniZaBrisanje);
                JOptionPane.showMessageDialog(this, "Zaposleni je uklonjen sa posla.");
                popuniTabelePoslovi(); // osvežava tabele poslova vezanih/van zadatka
                popuniTabeluZadaci();
                refreshAll();
            } else {
                JOptionPane.showMessageDialog(this, "Nije pronađeno zaposlenje za uklanjanje.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri uklanjanju zaposlenog sa posla: " + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonUkloniPosaoActionPerformed

    private void jButtonDodajPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajPosaoActionPerformed
        if (selektovaniZaposleni == null) {
            JOptionPane.showMessageDialog(this, "Nije selektovan zaposleni!");
            return;
        }

        int red = jTablePosloviNepovezani.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Nije selektovan posao za dodavanje.");
            return;
        }

        TableModelPoslovi modelBezZadatka = (TableModelPoslovi) jTablePosloviNepovezani.getModel();
        Posao selektovaniPosao = modelBezZadatka.getSelectedPosao(red);

        try {
            // Provera da li zaposleni već ima dodeljen posao
            ArrayList<Zaposlenje> svaZaposlenja = ClientController.getInstance().getAllZaposlenja();
            for (Zaposlenje z : svaZaposlenja) {
                if (z.getZaposleniID().equals(selektovaniZaposleni.getZaposleniID()) &&
                    z.getPosaoID().equals(selektovaniPosao.getPosaoID())) {
                    JOptionPane.showMessageDialog(this, "Zaposleni je već povezan sa ovim poslom.");
                    return;
                }
            }

            // Kreiranje novog zaposlenja: postavljamo datum početka na trenutni, datum završetka može biti null
            Zaposlenje novoZaposlenje = new Zaposlenje();
            novoZaposlenje.setZaposleniID(selektovaniZaposleni.getZaposleniID());
            novoZaposlenje.setPosaoID(selektovaniPosao.getPosaoID());
            novoZaposlenje.setDatumPocetkaZap(new java.util.Date());
            novoZaposlenje.setDatumZavrsetkaZap(null);

            ClientController.getInstance().addZaposlenje(novoZaposlenje);
            JOptionPane.showMessageDialog(this, "Zaposleni je dodat na posao.");
            popuniTabelePoslovi();
            popuniTabeluZadaci();
            refreshAll();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri dodavanju zaposlenog na posao: " + ex.getMessage());
        }

    }//GEN-LAST:event_jButtonDodajPosaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajPosao;
    private javax.swing.JButton jButtonIzmeniZaposlenog;
    private javax.swing.JButton jButtonNoviZaposleni;
    private javax.swing.JButton jButtonObrisiZaposlenog;
    private javax.swing.JButton jButtonOdustaniOdIzmene;
    private javax.swing.JButton jButtonUkloniPosao;
    private javax.swing.JComboBox jComboBoxListaZaposlenih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMenadzer;
    private javax.swing.JPasswordField jPasswordLozinkaZaposlenog;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablePosloviNepovezani;
    private javax.swing.JTable jTablePosloviPovezani;
    private javax.swing.JTable jTableZadaciZaposlenog;
    private javax.swing.JTextField jTextFieldEmailZaposlenog;
    private javax.swing.JTextField jTextFieldImeZaposlenog;
    private javax.swing.JTextField jTextFieldPrezimeZaposlenog;
    private javax.swing.JTextField jTextFieldTelefonZaposlenog;
    // End of variables declaration//GEN-END:variables

    private void refreshZaposleni(){
        try {
            zaposleni = ClientController.getInstance().getAllZaposleni();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju zaposlenih: " + ex.getMessage());
        }
    }
    
    private void omoguciIzmenu(boolean flag) {
        jTextFieldImeZaposlenog.setEditable(flag);
        jTextFieldPrezimeZaposlenog.setEditable(flag);
        jTextFieldTelefonZaposlenog.setEditable(flag);
        jTextFieldEmailZaposlenog.setEditable(flag);
        jPasswordLozinkaZaposlenog.setEditable(flag);
    }
    
    public void popuniComboBoxZaposleni() {
        refreshZaposleni();
        DefaultComboBoxModel<Zaposleni> model = new DefaultComboBoxModel<>();
        for (Zaposleni z : zaposleni) {
            model.addElement(z);
        }
        jComboBoxListaZaposlenih.setModel(model);
    }

    private void postaviListenerComboBoxZaposleni() {
        jComboBoxListaZaposlenih.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selektovaniZaposleni = (Zaposleni) jComboBoxListaZaposlenih.getSelectedItem();
                prikaziPodatkeOZaposlenom();
            }
        });
    }

    public void prikaziPodatkeOZaposlenom() {
        if (selektovaniZaposleni != null) {
            jComboBoxListaZaposlenih.setSelectedItem(selektovaniZaposleni);
            jTextFieldImeZaposlenog.setText(selektovaniZaposleni.getIme());
            jTextFieldPrezimeZaposlenog.setText(selektovaniZaposleni.getPrezime());
            jTextFieldTelefonZaposlenog.setText(selektovaniZaposleni.getTelefon());
            jTextFieldEmailZaposlenog.setText(selektovaniZaposleni.getEmail());
            jPasswordLozinkaZaposlenog.setText(selektovaniZaposleni.getLozinka());

            // Ako zaposleni ima vezanog menadžera, prikazujemo podatke o menadžeru
            try {
                Menadzer m = selektovaniZaposleni.getMenadzer();
                if(m != null) {
                    m = ClientController.getInstance().getMenadzer(m);
                    jLabelMenadzer.setText(m.getIme() + " " + m.getPrezime());
                } else {
                    jLabelMenadzer.setText("N/A");
                }
            } catch (Exception ex) {
                Logger.getLogger(FormZaposleni.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        popuniTabelePoslovi();
        popuniTabeluZadaci();
    }
    
    private void popuniTabeluZadaci() {
        try {
            if (selektovaniZaposleni == null) {
                return;
            }

            // 1. Učitaj sva zapošljavanja (angl. "employments")
            ArrayList<Zaposlenje> svaZaposlenja = ClientController.getInstance().getAllZaposlenja();
            // Filtriraj zapošljavanja gde je ZaposleniID jednak ID-u selektovanog zaposlenog
            ArrayList<Long> povezaniPosloviIds = new ArrayList<>();
            for (Zaposlenje z : svaZaposlenja) {
                if (z.getZaposleniID().equals(selektovaniZaposleni.getZaposleniID())) {
                    // Dodaj PosaoID samo ako nije već dodat (bez dupliranja)
                    if (!povezaniPosloviIds.contains(z.getPosaoID())) {
                        povezaniPosloviIds.add(z.getPosaoID());
                    }
                }
            }

            // 2. Učitaj sve pripadnosti zadatka-poslu
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            // Filtriraj pripadnosti gde je PosaoID u listi povezaniPosloviIds
            ArrayList<Long> zadaciIds = new ArrayList<>();
            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (povezaniPosloviIds.contains(p.getPosaoID())) {
                    if (!zadaciIds.contains(p.getZadatakID())) {
                        zadaciIds.add(p.getZadatakID());
                    }
                }
            }

            // 3. Učitaj sve zadatke
            ArrayList<Zadatak> sviZadaci = ClientController.getInstance().getAllZadaci();
            // Filtriraj zadatke koji su u listi zadaciIds
            ArrayList<Zadatak> zadaciZaZaposlenog = new ArrayList<>();
            for (Zadatak zadatak : sviZadaci) {
                if (zadaciIds.contains(zadatak.getZadatakID())) {
                    zadaciZaZaposlenog.add(zadatak);
                }
            }

            // 4. Postavi model tabele
            jTableZadaciZaposlenog.setModel(new models.TableModelZadaci(zadaciZaZaposlenog));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju zadataka: " + ex.getMessage());
        }
    }
  
    private void popuniTabelePoslovi() {
        try {
            if (selektovaniZaposleni == null) {
                return;
            }

            // Učitavanje svih poslova i zapošljavanja
            ArrayList<Posao> sviPoslovi = ClientController.getInstance().getAllPoslovi();
            ArrayList<Zaposlenje> svaZaposlenja = ClientController.getInstance().getAllZaposlenja();

            // Filter poslova koji su povezani sa izabranim zaposlenim
            ArrayList<Posao> posloviSaZaposlenim = new ArrayList<>();
            for (Zaposlenje z : svaZaposlenja) {
                if (z.getZaposleniID().equals(selektovaniZaposleni.getZaposleniID())) {
                    for (Posao posao : sviPoslovi) {
                        if (posao.getPosaoID().equals(z.getPosaoID())) {
                            posloviSaZaposlenim.add(posao);
                            break;
                        }
                    }
                }
            }

            // Poslovi koji nisu povezani sa izabranim zaposlenim
            ArrayList<Posao> posloviBezZaposlenog = new ArrayList<>(sviPoslovi);
            for (Posao p : posloviSaZaposlenim) {
                posloviBezZaposlenog.removeIf(pb -> pb.getPosaoID().equals(p.getPosaoID()));
            }

            // Postavljanje modela tabela
            TableModelPoslovi modelSaZaposlenim = new TableModelPoslovi(posloviSaZaposlenim);
            TableModelPoslovi modelBezZaposlenog = new TableModelPoslovi(posloviBezZaposlenog);
            jTablePosloviPovezani.setModel(modelSaZaposlenim);
            jTablePosloviNepovezani.setModel(modelBezZaposlenog);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju poslova: " + ex.getMessage());
        }
    }

    private void listenerInit(){
        // Listener za dvoklik na tabelu poslova SA zaposlenim
        jTablePosloviPovezani.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTablePosloviPovezani.getSelectedRow();
                    TableModelPoslovi model = (TableModelPoslovi) jTablePosloviPovezani.getModel();
                    if (red != -1 && red < model.getRowCount()) {
                        Posao selektovaniPosao = model.getSelectedPosao(red);
                        if (selektovaniPosao != null) {
                            otvoriFormuPosao(selektovaniPosao);  // Otvori formu za posao
                        }
                    }
                }
            }
        });

        // Listener za dvoklik na tabelu poslova BEZ zaposlenog
        jTablePosloviNepovezani.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTablePosloviNepovezani.getSelectedRow();
                    TableModelPoslovi model = (TableModelPoslovi) jTablePosloviNepovezani.getModel();
                    if (red != -1 && red < model.getRowCount()) {
                        Posao selektovaniPosao = model.getSelectedPosao(red);
                        if (selektovaniPosao != null) {
                            otvoriFormuPosao(selektovaniPosao);  // Otvori formu za posao
                        }
                    }
                }
            }
        });

        // Listener za dvostruki klik na tabelu zadataka zaposlenog
        jTableZadaciZaposlenog.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTableZadaciZaposlenog.getSelectedRow();
                    models.TableModelZadaci model = (models.TableModelZadaci) jTableZadaciZaposlenog.getModel();
                    if (red != -1 && red < model.getRowCount()) {
                        Zadatak selektovaniZadatak = model.getSelectedZadatak(red);
                        if (selektovaniZadatak != null) {
                            otvoriFormuZadatak(selektovaniZadatak);  // Otvori formu za zadatak
                        }
                    }
                }
            }
        });
    }
    
    private void otvoriFormuZadatak(Zadatak zad) {
        // Dobavi roditeljsku formu (MainFormMenadzer) preko SwingUtilities, a zatim pozovi setter na formi Zaposleni:
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if(win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            // Postavi selektovanog zaposlenog u FormZaposleni i prebaci karticu na Zaposleni panel
            mainForm.getFormZadatak().setSelectedZadatak(zad);
            mainForm.navigateToPanel("Zadatak");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }
    
    private void otvoriFormuPosao(Posao posao) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            // Pretpostavlja se da MainFormMenadzer ima metodu getFormZadatak() sa setter-om
            mainForm.getFormPosao().setSelectedPosao(posao);
            mainForm.navigateToPanel("Posao");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }

    public void setSelectedZaposleni(Zaposleni z) {
        selektovaniZaposleni = z;
        prikaziPodatkeOZaposlenom();
    }
    
    public void setLastZaposleni() {
        if (zaposleni != null && !zaposleni.isEmpty()) {
            Zaposleni poslednji = zaposleni.get(zaposleni.size() - 1);
            setSelectedZaposleni(poslednji);
            refreshAll();
        }
    }
    
    private void refreshAll() {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            mainForm.refreshAllMain();
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }

    public Zaposleni getSelektovaniZaposleni() {
        return selektovaniZaposleni;
    }

    public ArrayList<Zaposleni> getZaposleni() {
        return zaposleni;
    }

}
