/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package panels.FormZaposleni;

import controller.ClientController;
import domain.Menadzer;
import domain.Zaposleni;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author milos
 */
public class FormNoviZaposleni extends javax.swing.JDialog {
    private FormZaposleni parentForm;
    /**
     * Creates new form FormNoviZaposleni
     */
    public FormNoviZaposleni(java.awt.Frame parent, boolean modal, FormZaposleni parentForm) {
        super(parent, modal);
        initComponents();
        this.parentForm = parentForm;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldImeZaposlenog = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPrezimeZaposlenog = new javax.swing.JTextField();
        jTextFieldTelefonZaposlenog = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldEmailZaposlenog = new javax.swing.JTextField();
        jPasswordLozinka = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordPotvrdiLozinku = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButtonOdustani = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Ime:");

        jLabel10.setText("Prezime: ");

        jLabel11.setText("Telefon: ");

        jLabel12.setText("Email: ");

        jLabel13.setText("Lozinka: ");

        jLabel14.setText("Potvrdi Lozinku:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Novi Zaposleni");

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(133, 426, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordPotvrdiLozinku, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrezimeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTelefonZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmailZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonSacuvaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonOdustani)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldImeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPrezimeZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldTelefonZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldEmailZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jPasswordLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordPotvrdiLozinku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSacuvaj)
                    .addComponent(jButtonOdustani))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // Preuzimanje vrednosti iz forme
        String email = jTextFieldEmailZaposlenog.getText().trim();
        String ime = jTextFieldImeZaposlenog.getText().trim();
        String prezime = jTextFieldPrezimeZaposlenog.getText().trim();
        String telefon = jTextFieldTelefonZaposlenog.getText().trim();
        String lozinka = new String(jPasswordLozinka.getPassword()).trim();
        String potvrdiLozinku = new String(jPasswordPotvrdiLozinku.getPassword()).trim();

        // Provera da li su sva polja popunjena
        if(email.isEmpty() || ime.isEmpty() || prezime.isEmpty() || telefon.isEmpty() || lozinka.isEmpty() || potvrdiLozinku.isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");
            return;
        }

        // Provera da li se lozinka poklapa sa potvrdom
        if(!lozinka.equals(potvrdiLozinku)){
            JOptionPane.showMessageDialog(this, "Lozinke se ne poklapaju!");
            return;
        }

        // Provera da li zaposleni sa unetim email-om već postoji
        try {
            ArrayList<Zaposleni> zaposleniLista = ClientController.getInstance().getAllZaposleni();
            for(Zaposleni z : zaposleniLista){
                if(email.equals(z.getEmail())){
                    JOptionPane.showMessageDialog(this, "Zaposleni sa ovim email-om već postoji!");
                    return;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(FormNoviZaposleni.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Kreiranje novog zaposlenog i slanje zahteva ka serveru
        try {
            // Kreiranje novog zaposlenog – id je null
            Menadzer trenutniMenadzer = (Menadzer) ClientController.getInstance().getUlogovani();
            Zaposleni noviZaposleni = new Zaposleni(null, ime, prezime, telefon, email, lozinka, trenutniMenadzer);

            // Slanje zahteva ka serveru za kreiranje zaposlenog
            noviZaposleni = ClientController.getInstance().addZaposleni(noviZaposleni);

            // Ako je kreiranje uspešno, osvežavamo formu roditelja
            if (parentForm != null) {
                parentForm.popuniComboBoxZaposleni();
                parentForm.setLastZaposleni();
            }

            JOptionPane.showMessageDialog(this, "Zaposleni je uspešno kreiran!");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja zaposlenog: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordLozinka;
    private javax.swing.JPasswordField jPasswordPotvrdiLozinku;
    private javax.swing.JTextField jTextFieldEmailZaposlenog;
    private javax.swing.JTextField jTextFieldImeZaposlenog;
    private javax.swing.JTextField jTextFieldPrezimeZaposlenog;
    private javax.swing.JTextField jTextFieldTelefonZaposlenog;
    // End of variables declaration//GEN-END:variables
}
