/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels.FormPretraga;

import controller.ClientController;
import domain.Posao;
import domain.Zadatak;
import domain.Zaposleni;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import models.TableModelPretraga;
/**
 *
 * @author milos
 */
public class FormPretraga extends javax.swing.JPanel {

    /**
     * Creates new form FormPretraga
     */
    public FormPretraga() {
        initComponents();
        initListeners();
        dobrodosli();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTrazi = new javax.swing.JTextField();
        jButtonTrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pretraga");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonTrazi.setText("Trazi");
        jButtonTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTraziActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonTrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTraziActionPerformed
        pretrazi();
    }//GEN-LAST:event_jButtonTraziActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldTrazi;
    // End of variables declaration//GEN-END:variables

    private void dobrodosli(){
        jTextFieldTrazi.setText("Dobrodosli u TaskTracker!");
        pretrazi();
    }
    
    // Inicijalizacija listener-a za pretragu i dvostruki klik
    private void initListeners() {
        jButtonTrazi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pretrazi();
            }
        });

        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTable1.getSelectedRow();
                    if (red != -1) {
                        // Dohvati objekat iz modela
                        Object obj = ((TableModelPretraga) jTable1.getModel()).getLista().get(red);
                        // Otvori odgovarajući panel u zavisnosti od tipa objekta
                        if (obj instanceof Zaposleni) {
                            otvoriFormuZaposleni((Zaposleni) obj);
                        } else if (obj instanceof Posao) {
                            otvoriFormuPosao((Posao) obj);
                        } else if (obj instanceof Zadatak) {
                            otvoriFormuZadatak((Zadatak) obj);
                        }
                    }
                }
            }
        });
    }

    // Metoda za pretragu
    private void pretrazi() {
        String kriterijum = jTextFieldTrazi.getText().trim().toLowerCase();
        if (kriterijum.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite tekst za pretragu!");
            return;
        }

        List<Object> rezultati = new ArrayList<>();

        try {
            // Pretraga za zaposlene
            ArrayList<Zaposleni> zaposleni = ClientController.getInstance().getAllZaposleni();
            for (Zaposleni z : zaposleni) {
                String punoIme = (z.getIme() + " " + z.getPrezime()).toLowerCase();
                if (punoIme.contains(kriterijum)) {
                    rezultati.add(z);
                }
            }

            // Pretraga za poslove
            ArrayList<Posao> poslovi = ClientController.getInstance().getAllPoslovi();
            for (Posao p : poslovi) {
                if (p.getNazivPosla().toLowerCase().contains(kriterijum)) {
                    rezultati.add(p);
                }
            }

            // Pretraga za zadatke
            ArrayList<Zadatak> zadaci = ClientController.getInstance().getAllZadaci();
            for (Zadatak zad : zadaci) {
                if (zad.getNazivZadatka().toLowerCase().contains(kriterijum)) {
                    rezultati.add(zad);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom pretrage: " + ex.getMessage());
            return;
        }

        // Postavi model tabele sa rezultatima pretrage
        TableModelPretraga model = new TableModelPretraga(rezultati);
        jTable1.setModel(model);
    }

    // Primer implementacije metoda za otvaranje formi
    private void otvoriFormuZaposleni(Zaposleni zap) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            mainForm.getFormZaposleni().setSelectedZaposleni(zap);
            mainForm.switchPanel("Zaposleni");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }

    private void otvoriFormuPosao(Posao pos) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            mainForm.getFormPosao().setSelectedPosao(pos);
            mainForm.switchPanel("Posao");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }

    private void otvoriFormuZadatak(Zadatak zad) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            mainForm.getFormZadatak().setSelectedZadatak(zad);
            mainForm.switchPanel("Zadatak");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }
}