/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels.FormZadatak;

import controller.ClientController;
import domain.Menadzer;
import domain.Posao;
import domain.PripadnostZadatkaPoslu;
import domain.StatusZadatka;
import domain.Zadatak;
import domain.Zaposleni;
import domain.Zaposlenje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.TableModelPoslovi;

/**
 *
 * @author milos
 */
public class FormZadatak extends javax.swing.JPanel {
    private Zadatak selektovaniZadatak;
    private ArrayList<Zadatak> zadaci;

    /**
     * Creates new form FormZadatak
     */
    public FormZadatak() {
        initComponents();
        popuniComboBoxZadaci();
        postaviListenerComboBox();
        listenerInit();
        setLastZadatak();

        // Početno stanje – polja su neizmenjiva
        jTextFieldNazivZadatka.setEditable(false);
        jTextAreaOpisZadatka.setEditable(false);
        jComboBoxStatusZadatka.setEnabled(false);
        jButtonOdustaniOdIzmene.setVisible(false);
        
        // Popunjavanje combo boxa statusa sa vrednostima enum-a
        jComboBoxStatusZadatka.setModel(new DefaultComboBoxModel<>(StatusZadatka.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListaZadataka = new javax.swing.JComboBox();
        jButtonNoviPosao = new javax.swing.JButton();
        jTextFieldNazivZadatka = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOpisZadatka = new javax.swing.JTextArea();
        jButtonIzmeniZadatak = new javax.swing.JButton();
        jButtonObrisiZadatak = new javax.swing.JButton();
        jLabelMenadzer = new javax.swing.JLabel();
        jLabelDatumKreiranja = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePosloviPovezani = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePosloviNepovezani = new javax.swing.JTable();
        jButtonUkloniPosao = new javax.swing.JButton();
        jButtonDodajPosao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableZaposleniZadatka = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxStatusZadatka = new javax.swing.JComboBox();
        jButtonOdustaniOdIzmene = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zadatak");

        jLabel2.setText("Zadatak:");

        jComboBoxListaZadataka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonNoviPosao.setText("Novi Zadatak");
        jButtonNoviPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviPosaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Naziv Zadatka: ");

        jLabel4.setText("Opis Zadatka:");

        jTextAreaOpisZadatka.setColumns(20);
        jTextAreaOpisZadatka.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOpisZadatka);

        jButtonIzmeniZadatak.setText("Izmeni Zadatak");
        jButtonIzmeniZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniZadatakActionPerformed(evt);
            }
        });

        jButtonObrisiZadatak.setBackground(new java.awt.Color(255, 150, 150));
        jButtonObrisiZadatak.setText("Obrisi Zadatak");
        jButtonObrisiZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiZadatakActionPerformed(evt);
            }
        });

        jLabelMenadzer.setText("Menadzer");

        jLabelDatumKreiranja.setText("Datum Kreiranja");

        jLabel6.setText("Datum Kreiranja:");

        jLabel5.setText("Menadzer: ");

        jLabel7.setText("Poslovi:");

        jTablePosloviPovezani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePosloviPovezani);

        jTablePosloviNepovezani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTablePosloviNepovezani);

        jButtonUkloniPosao.setText("Ukloni Posao");
        jButtonUkloniPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUkloniPosaoActionPerformed(evt);
            }
        });

        jButtonDodajPosao.setText("Dodaj Posao");
        jButtonDodajPosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajPosaoActionPerformed(evt);
            }
        });

        jLabel8.setText("Zaposleni:");

        jTableZaposleniZadatka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableZaposleniZadatka);

        jLabel9.setText("Status Zadatka:");

        jComboBoxStatusZadatka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonOdustaniOdIzmene.setText("Odustani");
        jButtonOdustaniOdIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniOdIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUkloniPosao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDodajPosao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDatumKreiranja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonObrisiZadatak, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jComboBoxListaZadataka, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonNoviPosao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldNazivZadatka, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelMenadzer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOdustaniOdIzmene)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIzmeniZadatak, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxStatusZadatka, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(238, 238, 238))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxListaZadataka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonNoviPosao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNazivZadatka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonIzmeniZadatak)
                        .addComponent(jButtonOdustaniOdIzmene))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMenadzer)
                        .addComponent(jLabel5)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonObrisiZadatak)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDatumKreiranja)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxStatusZadatka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUkloniPosao)
                    .addComponent(jButtonDodajPosao))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNoviPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviPosaoActionPerformed
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent instanceof java.awt.Frame) {
            FormNoviZadatak forma = new FormNoviZadatak((java.awt.Frame) parent, true, this);
            forma.setVisible(true);
        } else {
            System.out.println("Parent nije JFrame ili Frame");
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNoviPosaoActionPerformed

    private void jButtonObrisiZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiZadatakActionPerformed
        int result = JOptionPane.showConfirmDialog(this, 
                "Da li ste sigurni da zelite da obrisete ovaj zadatak?", 
                "Konfirmacija", 
                JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }
        
        if (selektovaniZadatak == null) {
            JOptionPane.showMessageDialog(this, "Nije selektovan zadatak!");
            return;
        }
        
        // Prvo brisanje svih pripadnosti poslovima
        try {
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            for (PripadnostZadatkaPoslu prip : svePripadnosti) {
                if (prip.getZadatakID().equals(selektovaniZadatak.getZadatakID())) {
                    ClientController.getInstance().deletePripadnostZP(prip);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri brisanju pripadnosti zadacima: " + ex.getMessage());
            return; // Prekidamo izvršavanje ukoliko nastane greška
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                Zadatak zadatakZaBrisanje = (Zadatak) jComboBoxListaZadataka.getSelectedItem();
                ClientController.getInstance().deleteZadatak(zadatakZaBrisanje);
                popuniComboBoxZadaci();
                JOptionPane.showMessageDialog(this, "Uspesno obrisan zadatak.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ne mozete da obrisete ovaj zadatak: " + ex.getMessage());
            }
        }
        
        setLastZadatak();
    }//GEN-LAST:event_jButtonObrisiZadatakActionPerformed

    private void jButtonIzmeniZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniZadatakActionPerformed
        // Ako trenutno nije u režimu izmene (tekst je "Izmeni Zadatak")
        if (jButtonIzmeniZadatak.getText().equals("Izmeni Zadatak")) {
            omoguciIzmenu(true);
            jButtonIzmeniZadatak.setText("Sacuvaj");
            jButtonOdustaniOdIzmene.setVisible(true);
        } else {
            // U režimu "Sacuvaj", pokupimo izmene
            String noviNaziv = jTextFieldNazivZadatka.getText().trim();
            String noviOpis = jTextAreaOpisZadatka.getText().trim();

            if (noviNaziv.isEmpty() || noviOpis.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Naziv i opis ne mogu biti prazni!");
                return;
            }

            if (selektovaniZadatak == null) {
                JOptionPane.showMessageDialog(this, "Nije selektovan zadatak!");
                return;
            }

            try {
                ArrayList<Zadatak> sviZadaci = ClientController.getInstance().getAllZadaci();
                for (Zadatak z : sviZadaci) {
                    // Provera da ne postoji drugi zadatak sa istim nazivom
                    if (noviNaziv.equals(z.getNazivZadatka()) && !noviNaziv.equals(selektovaniZadatak.getNazivZadatka())) {
                        JOptionPane.showMessageDialog(this, "Zadatak sa ovim nazivom već postoji!");
                        return;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(FormNoviZadatak.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Postavljanje novih vrednosti
            selektovaniZadatak.setNazivZadatka(noviNaziv);
            selektovaniZadatak.setOpisZadatka(noviOpis);
            // Preuzimamo izabran status iz combo boxa
            StatusZadatka noviStatus = (StatusZadatka) jComboBoxStatusZadatka.getSelectedItem();
            selektovaniZadatak.setStatusZadatka(noviStatus);

            try {
                ClientController.getInstance().updateZadatak(selektovaniZadatak);
                JOptionPane.showMessageDialog(this, "Zadatak je uspešno izmenjen!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greška prilikom izmene zadatka: " + ex.getMessage());
                Logger.getLogger(FormZadatak.class.getName()).log(Level.SEVERE, null, ex);
            }

            omoguciIzmenu(false);
            jButtonIzmeniZadatak.setText("Izmeni Zadatak");
            jButtonOdustaniOdIzmene.setVisible(false);
            popuniComboBoxZadaci();
            refreshAll();
        }
    }//GEN-LAST:event_jButtonIzmeniZadatakActionPerformed

    private void jButtonOdustaniOdIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniOdIzmeneActionPerformed
        prikaziPodatkeOZadatku();
        omoguciIzmenu(false);
        jButtonIzmeniZadatak.setText("Izmeni Zadatak");
        jButtonOdustaniOdIzmene.setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniOdIzmeneActionPerformed

    private void jButtonDodajPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajPosaoActionPerformed
        if (selektovaniZadatak == null) {
            JOptionPane.showMessageDialog(this, "Nije selektovan zadatak!");
            return;
        }

        int red = jTablePosloviNepovezani.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Nije selektovan posao za dodavanje.");
            return;
        }

        TableModelPoslovi modelBezZadatka = (TableModelPoslovi) jTablePosloviNepovezani.getModel();
        Posao selektovaniPosao = modelBezZadatka.getSelectedPosao(red);

        try {
            // Provera da li veza (pripadnost) već postoji
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (p.getZadatakID().equals(selektovaniZadatak.getZadatakID()) &&
                    p.getPosaoID().equals(selektovaniPosao.getPosaoID())) {
                    JOptionPane.showMessageDialog(this, "Posao je već povezan sa ovim zadatkom.");
                    return;
                }
            }

            // Kreiranje nove pripadnosti: postavljamo datum početka na trenutni, datum završetka može biti null
            PripadnostZadatkaPoslu novaPripadnost = new PripadnostZadatkaPoslu();
            novaPripadnost.setZadatakID(selektovaniZadatak.getZadatakID());
            novaPripadnost.setPosaoID(selektovaniPosao.getPosaoID());
            novaPripadnost.setDatumPocetkaPrip(new java.util.Date());
            novaPripadnost.setDatumZavrsetkaPrip(null);

            ClientController.getInstance().addPripadnostZP(novaPripadnost);
            JOptionPane.showMessageDialog(this, "Posao je dodat na zadatak.");
            popuniTabelePoslovi();
            popuniTabeluZaposleni();
            refreshAll();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri dodavanju posla: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDodajPosaoActionPerformed

    private void jButtonUkloniPosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUkloniPosaoActionPerformed
        if (selektovaniZadatak == null) {
            JOptionPane.showMessageDialog(this, "Nije selektovan zadatak!");
            return;
        }

        int red = jTablePosloviPovezani.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Nije selektovan posao za uklanjanje.");
            return;
        }

        TableModelPoslovi modelPoslovi = (TableModelPoslovi) jTablePosloviPovezani.getModel();
        Posao selektovaniPosao = modelPoslovi.getSelectedPosao(red);

        try {
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            PripadnostZadatkaPoslu pripZaBrisanje = null;

            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (p.getZadatakID().equals(selektovaniZadatak.getZadatakID()) &&
                    p.getPosaoID().equals(selektovaniPosao.getPosaoID())) {
                    pripZaBrisanje = p;
                    break;
                }
            }

            if (pripZaBrisanje != null) {
                ClientController.getInstance().deletePripadnostZP(pripZaBrisanje);
                JOptionPane.showMessageDialog(this, "Posao je uklonjen sa zadatka.");
                popuniTabelePoslovi(); // osvežava tabele poslova vezanih/van zadatka
                popuniTabeluZaposleni();
                refreshAll();
            } else {
                JOptionPane.showMessageDialog(this, "Nije pronađena pripadnost za uklanjanje.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri uklanjanju posla: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonUkloniPosaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajPosao;
    private javax.swing.JButton jButtonIzmeniZadatak;
    private javax.swing.JButton jButtonNoviPosao;
    private javax.swing.JButton jButtonObrisiZadatak;
    private javax.swing.JButton jButtonOdustaniOdIzmene;
    private javax.swing.JButton jButtonUkloniPosao;
    private javax.swing.JComboBox jComboBoxListaZadataka;
    private javax.swing.JComboBox jComboBoxStatusZadatka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDatumKreiranja;
    private javax.swing.JLabel jLabelMenadzer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablePosloviNepovezani;
    private javax.swing.JTable jTablePosloviPovezani;
    private javax.swing.JTable jTableZaposleniZadatka;
    private javax.swing.JTextArea jTextAreaOpisZadatka;
    private javax.swing.JTextField jTextFieldNazivZadatka;
    // End of variables declaration//GEN-END:variables

    private void omoguciIzmenu(boolean flag) {
        jTextFieldNazivZadatka.setEditable(flag);
        jTextAreaOpisZadatka.setEditable(flag);
        jComboBoxStatusZadatka.setEnabled(flag);
    }
    
    private void refreshZadaci() {
        try {
            zadaci = ClientController.getInstance().getAllZadaci();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju zadataka: " + ex.getMessage());
        }
    }
    
    public void popuniComboBoxZadaci() {
        refreshZadaci();
        DefaultComboBoxModel<Zadatak> model = new DefaultComboBoxModel<>();
        for (Zadatak z : zadaci) {
            model.addElement(z);
        }
        jComboBoxListaZadataka.setModel(model);
    }

    private void postaviListenerComboBox() {
        jComboBoxListaZadataka.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setSelectedZadatak((Zadatak) jComboBoxListaZadataka.getSelectedItem());
                prikaziPodatkeOZadatku();
            }
        });
    }
        
    public void prikaziPodatkeOZadatku() {
        if (selektovaniZadatak != null) {
            jComboBoxListaZadataka.setSelectedItem(selektovaniZadatak);
            jTextFieldNazivZadatka.setText(selektovaniZadatak.getNazivZadatka());
            jTextAreaOpisZadatka.setText(selektovaniZadatak.getOpisZadatka());
            
            Menadzer m = selektovaniZadatak.getMenadzer();
            if (m != null) {
                jLabelMenadzer.setText(m.getIme() + " " + m.getPrezime());
            } else {
                jLabelMenadzer.setText("N/A");
            }
            
            jLabelDatumKreiranja.setText(selektovaniZadatak.getDatumKreiranjaZadatka().toString());
            jComboBoxStatusZadatka.setSelectedItem(selektovaniZadatak.getStatusZadatka());
        }
        
        popuniTabelePoslovi();
        popuniTabeluZaposleni();
    }
    
    private void popuniTabeluZaposleni() {
        try {
            if (selektovaniZadatak == null) {
                return;
            }

            // 1. Učitaj sve pripadnosti zadatka-poslu
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();
            // Filtriraj pripadnosti gde je ZadatakID jednak ID-ju selektovanog zadatka
            ArrayList<Long> povezaniPosloviIds = new ArrayList<>();
            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (p.getZadatakID().equals(selektovaniZadatak.getZadatakID())) {
                    // Dodaj PosaoID samo ako nije već dodat (bez dupliranja)
                    if (!povezaniPosloviIds.contains(p.getPosaoID())) {
                        povezaniPosloviIds.add(p.getPosaoID());
                    }
                }
            }

            // 2. Učitaj sva zaposlenja (angl. "employments")
            ArrayList<Zaposlenje> svaZaposljenja = ClientController.getInstance().getAllZaposlenja();
            // Iz zaposlenja izdvoji jedinstvene ZaposleniID-je koji su povezani sa poslovima iz povezaniPosloviIds
            ArrayList<Long> zaposleniIds = new ArrayList<>();
            for (Zaposlenje z : svaZaposljenja) {
                if (povezaniPosloviIds.contains(z.getPosaoID())) {
                    if (!zaposleniIds.contains(z.getZaposleniID())) {
                        zaposleniIds.add(z.getZaposleniID());
                    }
                }
            }

            // 3. Učitaj sve zaposlene
            ArrayList<Zaposleni> sviZaposleni = ClientController.getInstance().getAllZaposleni();
            // Filtriraj samo one zaposlene čiji ID se nalazi u listi zaposleniIds
            ArrayList<Zaposleni> zaposleniZaZadatak = new ArrayList<>();
            for (Zaposleni zap : sviZaposleni) {
                if (zaposleniIds.contains(zap.getZaposleniID())) {
                    zaposleniZaZadatak.add(zap);
                }
            }

            // 4. Postavi model tabele (bez duplikata)
            jTableZaposleniZadatka.setModel(new models.TableModelZaposleni(zaposleniZaZadatak));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju zaposlenih: " + ex.getMessage());
        }
    }
 
    private void popuniTabelePoslovi() {
        try {
            if (selektovaniZadatak == null) {
                return;
            }

            // Učitavanje svih poslova i pripadnosti
            ArrayList<Posao> sviPoslovi = ClientController.getInstance().getAllPoslovi();
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();

            // Filter poslova koji sadrže izabrani zadatak
            ArrayList<Posao> posloviSaZadatkom = new ArrayList<>();
            for (PripadnostZadatkaPoslu p : svePripadnosti) {
                if (p.getZadatakID().equals(selektovaniZadatak.getZadatakID())) {
                    for (Posao posao : sviPoslovi) {
                        if (posao.getPosaoID().equals(p.getPosaoID())) {
                            posloviSaZadatkom.add(posao);
                            break;
                        }
                    }
                }
            }

            // Poslovi koji nemaju ovaj zadatak
            ArrayList<Posao> posloviBezZadatka = new ArrayList<>(sviPoslovi);
            for (Posao p : posloviSaZadatkom) {
                posloviBezZadatka.removeIf(pb -> pb.getPosaoID().equals(p.getPosaoID()));
            }

            // Postavljanje modela tabela
            TableModelPoslovi modelSaZadatkom = new TableModelPoslovi(posloviSaZadatkom);
            TableModelPoslovi modelBezZadatka = new TableModelPoslovi(posloviBezZadatka);
            jTablePosloviPovezani.setModel(modelSaZadatkom);
            jTablePosloviNepovezani.setModel(modelBezZadatka);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju poslova: " + ex.getMessage());
        }
    }
    
    private void listenerInit(){
        // Listener za dvoklik na tabelu poslova SA zadatkom
        jTablePosloviPovezani.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTablePosloviPovezani.getSelectedRow();
                    TableModelPoslovi model = (TableModelPoslovi) jTablePosloviPovezani.getModel();
                    if (red != -1 && red < model.getRowCount()) {
                        Posao selektovaniPosao = model.getSelectedPosao(red);
                        if (selektovaniPosao != null) {
                            otvoriFormuPosao(selektovaniPosao);
                        }
                    }
                }
            }
        });

        // Listener za dvoklik na tabelu poslova BEZ zadatka
        jTablePosloviNepovezani.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTablePosloviNepovezani.getSelectedRow();
                    TableModelPoslovi model = (TableModelPoslovi) jTablePosloviNepovezani.getModel();
                    if (red != -1 && red < model.getRowCount()) {
                        Posao selektovaniPosao = model.getSelectedPosao(red);
                        if (selektovaniPosao != null) {
                            otvoriFormuPosao(selektovaniPosao);
                        }
                    }
                }
            }
        });
        
        // Listener za dvostruki klik na tabelu zaposlenih povezanih sa zadatkom
        jTableZaposleniZadatka.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int red = jTableZaposleniZadatka.getSelectedRow();
                    models.TableModelZaposleni model = (models.TableModelZaposleni) jTableZaposleniZadatka.getModel();
                    if (red != -1 && red < model.getRowCount()) {
                        Zaposleni selektovaniZaposleni = model.getSelectedZaposleni(red);
                        if (selektovaniZaposleni != null) {
                            otvoriFormuZaposleni(selektovaniZaposleni);
                        }
                    }
                }
            }
        });
    }
    
    private void otvoriFormuZaposleni(Zaposleni zap) {
        // Dobavi roditeljsku formu (MainFormMenadzer) preko SwingUtilities, a zatim pozovi setter na formi Zaposleni:
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if(win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            // Postavi selektovanog zaposlenog u FormZaposleni i prebaci karticu na Zaposleni panel
            mainForm.getFormZaposleni().setSelectedZaposleni(zap);
            mainForm.navigateToPanel("Zaposleni");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }
    
    private void otvoriFormuPosao(Posao posao) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            // Pretpostavlja se da MainFormMenadzer ima metodu getFormZadatak() sa setter-om
            mainForm.getFormPosao().setSelectedPosao(posao);
            mainForm.navigateToPanel("Posao");
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }
    
    public void setSelectedZadatak(Zadatak z) {
        selektovaniZadatak = z;
        prikaziPodatkeOZadatku();
    }
    
    public void setLastZadatak() {
        if (zadaci != null && !zadaci.isEmpty()) {
            Zadatak poslednji = zadaci.get(zadaci.size() - 1);
            setSelectedZadatak(poslednji);
            refreshAll();
        }
    }
    
    private void refreshAll() {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof forms.MainFormMenadzer) {
            forms.MainFormMenadzer mainForm = (forms.MainFormMenadzer) win;
            mainForm.refreshAllMain();
        } else {
            System.out.println("Nije pronađena instanca MainFormMenadzer!");
        }
    }

    public Zadatak getSelektovaniZadatak() {
        return selektovaniZadatak;
    }

    public ArrayList<Zadatak> getZadaci() {
        return zadaci;
    }
    
    
}
