/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domain.Zaposleni;

import controller.ClientController;
import domain.Posao;
import domain.PripadnostZadatkaPoslu;
import domain.StatusZadatka;
import domain.Zadatak;
import domain.Zaposleni;
import domain.Zaposlenje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import models.TableModelZadaci;
/**
 *
 * @author milos
 */
public class MainFormZaposleni extends javax.swing.JFrame {

    private Zaposleni ulogovaniZaposleni;
    private TableModelZadaci tableModel;
    /**
     * Creates new form MainFormZaposleni
     * @param ulogovaniZaposleni
     */
    public MainFormZaposleni(Zaposleni ulogovaniZaposleni) {
        this.ulogovaniZaposleni = ulogovaniZaposleni;
        initComponents();
        initListeners();
        popuniInformacijeOZaposlenom();
        popuniPosloviComboBox();
        refreshZadaciTable();
        
        // Popunjavanje combo boxa statusa sa vrednostima enum-a
        jComboBoxStatus.setModel(new DefaultComboBoxModel<>(StatusZadatka.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImePrezime = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelefon = new javax.swing.JLabel();
        jComboBoxPoslovi = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxSviPoslovi = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableZadaciZaposlenog = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonIzadji = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOpisZadatka = new javax.swing.JTextArea();
        jButtonOsvezi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelImePrezime.setText("Ime Prezime");

        jLabelEmail.setText("Email");

        jLabelTelefon.setText("Telefon");

        jComboBoxPoslovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Lista Poslova: ");

        jCheckBoxSviPoslovi.setText("Svi Poslovi");

        jTableZadaciZaposlenog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableZadaciZaposlenog);

        jLabel2.setText("Status: ");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonIzadji.setBackground(new java.awt.Color(255, 150, 150));
        jButtonIzadji.setText("Izadji");
        jButtonIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzadjiActionPerformed(evt);
            }
        });

        jTextAreaOpisZadatka.setColumns(20);
        jTextAreaOpisZadatka.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOpisZadatka);

        jButtonOsvezi.setText("Osvezi");
        jButtonOsvezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOsveziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(jComboBoxPoslovi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addComponent(jCheckBoxSviPoslovi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelImePrezime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPoslovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxSviPoslovi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSacuvaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzadji)
                    .addComponent(jButtonOsvezi))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzadjiActionPerformed
        dispose();
        new LoginForma().setVisible(true);
    }//GEN-LAST:event_jButtonIzadjiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        int selectedRow = jTableZadaciZaposlenog.getSelectedRow();
            if(selectedRow >= 0){
                Zadatak selectedZadatak = tableModel.getSelectedZadatak(selectedRow);
                StatusZadatka newStatus = (StatusZadatka) jComboBoxStatus.getSelectedItem();
                selectedZadatak.setStatusZadatka(newStatus);
                try {
                    ClientController.getInstance().updateZadatak(selectedZadatak);
                    JOptionPane.showMessageDialog(MainFormZaposleni.this, "Status zadatka je uspešno izmenjen!");
                    refreshZadaciTable();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(MainFormZaposleni.this, "Greška prilikom izmene zadatka: " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(MainFormZaposleni.this, "Morate odabrati zadatak iz tabele!");
            }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonOsveziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOsveziActionPerformed
        try {
            Zaposleni noviUlogovaniZaposleni = ClientController.getInstance().getZaposleni(ulogovaniZaposleni);
            ulogovaniZaposleni = noviUlogovaniZaposleni;
            popuniInformacijeOZaposlenom();
            popuniPosloviComboBox();
            refreshZadaciTable();
        } catch (Exception ex) {
            Logger.getLogger(MainFormZaposleni.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOsveziActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzadji;
    private javax.swing.JButton jButtonOsvezi;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JCheckBox jCheckBoxSviPoslovi;
    private javax.swing.JComboBox jComboBoxPoslovi;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelImePrezime;
    private javax.swing.JLabel jLabelTelefon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableZadaciZaposlenog;
    private javax.swing.JTextArea jTextAreaOpisZadatka;
    // End of variables declaration//GEN-END:variables

    private void popuniInformacijeOZaposlenom() {
        jLabelImePrezime.setText(ulogovaniZaposleni.getIme() + " " + ulogovaniZaposleni.getPrezime());
        jLabelEmail.setText(ulogovaniZaposleni.getEmail());
        jLabelTelefon.setText(ulogovaniZaposleni.getTelefon());
    }
    
    private void popuniStatusComboBox() {
        jComboBoxStatus.removeAllItems();
        // Pretpostavljamo da je StatusZadatka enum – ukoliko nije, prilagodite ovu logiku
        for (StatusZadatka status : StatusZadatka.values()) {
            jComboBoxStatus.addItem(status);
        }
    }


    private void popuniPosloviComboBox() {
        try {
            
            ArrayList<Posao> sviPoslovi = ClientController.getInstance().getAllPoslovi();
            ArrayList<Zaposlenje> svaZaposlenja = ClientController.getInstance().getAllZaposlenja();

            // Filter poslova koji su povezani sa izabranim zaposlenim
            ArrayList<Posao> posloviSaZaposlenim = new ArrayList<>();
            for (Zaposlenje z : svaZaposlenja) {
                if (z.getZaposleniID().equals(ulogovaniZaposleni.getZaposleniID())) {
                    for (Posao posao : sviPoslovi) {
                        if (posao.getPosaoID().equals(z.getPosaoID())) {
                            posloviSaZaposlenim.add(posao);
                            break;
                        }
                    }
                }
            }
            jComboBoxPoslovi.removeAllItems();
            for (Posao posao : posloviSaZaposlenim) {
                jComboBoxPoslovi.addItem(posao);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja poslova: " + ex.getMessage());
        }
    }

    private void refreshZadaciTable() {
        try {
            if (ulogovaniZaposleni == null) {
                return;
            }

            ArrayList<Zadatak> zadaciZaZaposlenog = new ArrayList<>();
            ArrayList<PripadnostZadatkaPoslu> svePripadnosti = ClientController.getInstance().getAllPripadnostiZP();

            if (jCheckBoxSviPoslovi.isSelected()) {
                // Svi poslovi – filtriraj zadatke kroz sva zapošljavanja povezana sa zaposlenim:
                ArrayList<Zaposlenje> svaZaposlenja = ClientController.getInstance().getAllZaposlenja();
                ArrayList<Long> povezaniPosloviIds = new ArrayList<>();
                for (Zaposlenje z : svaZaposlenja) {
                    if (z.getZaposleniID().equals(ulogovaniZaposleni.getZaposleniID())) {
                        if (!povezaniPosloviIds.contains(z.getPosaoID())) {
                            povezaniPosloviIds.add(z.getPosaoID());
                        }
                    }
                }

                ArrayList<Long> zadaciIds = new ArrayList<>();
                for (PripadnostZadatkaPoslu p : svePripadnosti) {
                    if (povezaniPosloviIds.contains(p.getPosaoID())) {
                        if (!zadaciIds.contains(p.getZadatakID())) {
                            zadaciIds.add(p.getZadatakID());
                        }
                    }
                }

                ArrayList<Zadatak> sviZadaci = ClientController.getInstance().getAllZadaci();
                for (Zadatak zadatak : sviZadaci) {
                    if (zadaciIds.contains(zadatak.getZadatakID())) {
                        zadaciZaZaposlenog.add(zadatak);
                    }
                }
            } else {
                // Specifičan posao – filtriraj zadatke samo za izabrani posao:
                Posao selectedPosao = (Posao) jComboBoxPoslovi.getSelectedItem();
                if (selectedPosao != null) {
                    ArrayList<Long> zadaciIds = new ArrayList<>();
                    for (PripadnostZadatkaPoslu p : svePripadnosti) {
                        if (p.getPosaoID().equals(selectedPosao.getPosaoID())) {
                            if (!zadaciIds.contains(p.getZadatakID())) {
                                zadaciIds.add(p.getZadatakID());
                            }
                        }
                    }
                    ArrayList<Zadatak> sviZadaci = ClientController.getInstance().getAllZadaci();
                    for (Zadatak zadatak : sviZadaci) {
                        if (zadaciIds.contains(zadatak.getZadatakID())) {
                            zadaciZaZaposlenog.add(zadatak);
                        }
                    }
                }
            }

            // Ažuriraj model tabele
            jTableZadaciZaposlenog.setModel(new models.TableModelZadaci(zadaciZaZaposlenog));
            tableModel.fireTableDataChanged();

            // Resetuj selekciju i polja za prikaz opisa/statusa
            jTableZadaciZaposlenog.clearSelection();
            jTextAreaOpisZadatka.setText("");
            if (jComboBoxStatus.getItemCount() > 0) {
                jComboBoxStatus.setSelectedIndex(0);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju zadataka: " + ex.getMessage());
        }
    }
  
    private void initListeners() {
        // Inicijalizacija modela tabele (prazan ili po filteru)
        tableModel = new TableModelZadaci(new ArrayList<>());
        jTableZadaciZaposlenog.setModel(tableModel);
        
        // Kada se checkbox "Svi poslovi" klikne, combo box se onemogućava ili omogućava, a tabela se ažurira
        jCheckBoxSviPoslovi.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean allSelected = jCheckBoxSviPoslovi.isSelected();
                jComboBoxPoslovi.setEnabled(!allSelected);
                refreshZadaciTable();
            }
        });
        
        // Kada se odabere posao iz combo boxa (ako nije odabran "Svi poslovi"), tabela se ažurira
        jComboBoxPoslovi.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                if(!jCheckBoxSviPoslovi.isSelected()){
                    refreshZadaciTable();
                }
            }
        });
        
        // Kada se odabere red u tabeli, prikazuje se opis zadatka i postavlja se trenutno stanje u combo box statusa
        jTableZadaciZaposlenog.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()){
                    int selectedRow = jTableZadaciZaposlenog.getSelectedRow();
                    if(selectedRow >= 0){
                        tableModel = (TableModelZadaci) jTableZadaciZaposlenog.getModel();
                        Zadatak selectedZadatak = tableModel.getSelectedZadatak(selectedRow);
                        jTextAreaOpisZadatka.setText(selectedZadatak.getOpisZadatka());
                        jComboBoxStatus.setSelectedItem(selectedZadatak.getStatusZadatka());
                    }
                }
            }
        });
        
        // Dugme za čuvanje izmenjenog statusa zadatka – šalje update zahtev
        jButtonSacuvaj.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = jTableZadaciZaposlenog.getSelectedRow();
                if(selectedRow >= 0){
                    Zadatak selectedZadatak = tableModel.getSelectedZadatak(selectedRow);
                    StatusZadatka newStatus = (StatusZadatka) jComboBoxStatus.getSelectedItem();
                    selectedZadatak.setStatusZadatka(newStatus);
                    try {
                        ClientController.getInstance().updateZadatak(selectedZadatak);
                        JOptionPane.showMessageDialog(MainFormZaposleni.this, "Status zadatka je uspešno izmenjen!");
                        refreshZadaciTable();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(MainFormZaposleni.this, "Greška prilikom izmene zadatka: " + ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(MainFormZaposleni.this, "Morate odabrati zadatak iz tabele!");
                }
            }
        });
    }
}