/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package forms;

import domain.Menadzer;
import domain.Posao;
import domain.Zadatak;
import domain.Zaposleni;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import javax.swing.JPanel;
import panels.FormPosao.FormPosao;
import panels.FormPretraga.FormPretraga;
import panels.FormZadatak.FormZadatak;
import panels.FormZaposleni.FormZaposleni;
/**
 *
 * @author milos
 */
public class MainFormMenadzer extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private Menadzer ulogovaniMenadzer;
    private FormZaposleni formZaposleni;
    private FormZadatak formZadatak;
    private FormPosao formPosao;
    private FormPretraga formPretraga;
    private Stack<NavigationItem> navigationStack = new Stack<>();
    private boolean isNavigatingBack = false;

    /** Creates new form MainFormMenadzer
     * @param ulogovaniMenadzer */
    public MainFormMenadzer(Menadzer ulogovaniMenadzer) {
        this.ulogovaniMenadzer = ulogovaniMenadzer;
        initComponents();
        setupCardLayout();
        setupButtonActions();
        switchPanel("Pretraga");
        setLocationRelativeTo(null);
        jButtonNazad.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jButtonPosao = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jButtonZadaci = new javax.swing.JButton();
        jButtonZaposleni = new javax.swing.JButton();
        jButtonPretraga = new javax.swing.JButton();
        jButtonIzadji = new javax.swing.JButton();
        jButtonOsvezi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButtonPosao.setBackground(new java.awt.Color(242, 242, 242));
        jButtonPosao.setText("Posao");
        jButtonPosao.setBorderPainted(false);

        jButtonNazad.setBackground(new java.awt.Color(242, 242, 242));
        jButtonNazad.setText("Nazad");
        jButtonNazad.setBorderPainted(false);

        jButtonZadaci.setBackground(new java.awt.Color(242, 242, 242));
        jButtonZadaci.setText("Zadaci");
        jButtonZadaci.setBorderPainted(false);

        jButtonZaposleni.setBackground(new java.awt.Color(242, 242, 242));
        jButtonZaposleni.setText("Zaposleni");
        jButtonZaposleni.setBorderPainted(false);

        jButtonPretraga.setBackground(new java.awt.Color(242, 242, 242));
        jButtonPretraga.setText("Pretraga");
        jButtonPretraga.setBorderPainted(false);

        jButtonIzadji.setBackground(new java.awt.Color(255, 150, 150));
        jButtonIzadji.setText("Izadji");
        jButtonIzadji.setBorderPainted(false);

        jButtonOsvezi.setBackground(new java.awt.Color(242, 242, 242));
        jButtonOsvezi.setText("Osvezi");
        jButtonOsvezi.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPosao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonZadaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOsvezi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPretraga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPosao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonZadaci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonZaposleni)
                        .addGap(8, 8, 8)
                        .addComponent(jButtonOsvezi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNazad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIzadji)
                        .addGap(0, 536, Short.MAX_VALUE))
                    .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzadji;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonOsvezi;
    private javax.swing.JButton jButtonPosao;
    private javax.swing.JButton jButtonPretraga;
    private javax.swing.JButton jButtonZadaci;
    private javax.swing.JButton jButtonZaposleni;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables

private void setupCardLayout() {
        cardLayout = new CardLayout();
        jPanelMain.setLayout(cardLayout);

        formZaposleni = new FormZaposleni();
        formPosao = new FormPosao();
        formZadatak = new FormZadatak();
        formPretraga = new FormPretraga();

        formZaposleni.setName("Zaposleni");
        formPosao.setName("Posao");
        formZadatak.setName("Zadatak");
        formPretraga.setName("Pretraga");

        jPanelMain.add(formZaposleni, "Zaposleni");
        jPanelMain.add(formPosao, "Posao");
        jPanelMain.add(formZadatak, "Zadatak");
        jPanelMain.add(formPretraga, "Pretraga");
    }

    private void setupButtonActions() {
        jButtonZaposleni.addActionListener((ActionEvent e) -> {
            navigateToPanel("Zaposleni");
        });

        jButtonPosao.addActionListener((ActionEvent e) -> {
            navigateToPanel("Posao");
        });

        jButtonZadaci.addActionListener((ActionEvent e) -> {
            navigateToPanel("Zadatak");
        });

        jButtonPretraga.addActionListener((ActionEvent e) -> {
            navigateToPanel("Pretraga");
        });

        jButtonOsvezi.addActionListener((ActionEvent e) -> {
            osveziSveSaBaze();
        });
        
        jButtonNazad.addActionListener((ActionEvent e) -> {
            nazad();
        });

        jButtonIzadji.addActionListener((ActionEvent e) -> {
            dispose();
            new LoginForma().setVisible(true);
        });
    }

    public void switchPanel(String panelName) {
        cardLayout.show(jPanelMain, panelName);
    }

    public void addNavigationItem(String panelName, Object selectedObject) {
        if (isNavigatingBack) return;
        navigationStack.push(new NavigationItem(panelName, selectedObject));
        System.out.println("Adding navigation item: Panel=" + panelName + ", Selected Object=" + selectedObject);
        jButtonNazad.setEnabled(true);
    }

    private void nazad() {
        if (navigationStack.isEmpty()) {
            jButtonNazad.setEnabled(false);
            return;
        }

        NavigationItem current = navigationStack.peek();
        System.out.println("New top of stack: Panel = " + current.getPanelName() + ", Selected Object = " + current.getSelectedObject());

        isNavigatingBack = true;
        switchPanel(current.getPanelName());

        switch (current.getPanelName()) {
            case "Zaposleni":
                if (current.getSelectedObject() instanceof Zaposleni) {
                    formZaposleni.setSelectedZaposleni((Zaposleni) current.getSelectedObject());
                }
                break;
            case "Posao":
                if (current.getSelectedObject() instanceof Posao) {
                    formPosao.setSelectedPosao((Posao) current.getSelectedObject());
                }
                break;
            case "Zadatak":
                if (current.getSelectedObject() instanceof Zadatak) {
                    formZadatak.setSelectedZadatak((Zadatak) current.getSelectedObject());
                }
                break;
        }

        isNavigatingBack = false;
        
        NavigationItem removed = navigationStack.pop();
        System.out.println("Removed navigation item: Panel = " + removed.getPanelName() + ", Selected Object = " + removed.getSelectedObject());

        if (navigationStack.isEmpty()) {
            jButtonNazad.setEnabled(false);
        }
    }

    public String getCurrentPanelName() {
        for (Component comp : jPanelMain.getComponents()) {
            if (comp.isVisible()) {
                return comp.getName();
            }
        }
        return null;
    }

    public void navigateToPanel(String newPanelName) {
        String currentPanelName = getCurrentPanelName();
        Object selectedObject = null;

        if (currentPanelName != null) {
            switch (currentPanelName) {
                case "Zaposleni":
                    selectedObject = formZaposleni.getSelektovaniZaposleni();
                    break;
                case "Posao":
                    selectedObject = formPosao.getSelektovaniPosao();
                    break;
                case "Zadatak":
                    selectedObject = formZadatak.getSelektovaniZadatak();
                    break;
            }

            addNavigationItem(currentPanelName, selectedObject);
        }

        switchPanel(newPanelName);
    }

    public FormZaposleni getFormZaposleni() {
        return formZaposleni;
    }

    public FormZadatak getFormZadatak() {
        return formZadatak;
    }

    public FormPosao getFormPosao() {
        return formPosao;
    }

    public void refreshAllMain() {
        formPosao.prikaziPodatkeOPoslu();
        formZadatak.prikaziPodatkeOZadatku();
        formZaposleni.prikaziPodatkeOZaposlenom();
    }
    
    public void osveziSveSaBaze() {
        // === POSAO ===
        Posao selektovaniPosao = formPosao.getSelektovaniPosao();
        formPosao.popuniComboBoxPoslovi();
        boolean selektovaniPosaoJeUListi = false;
        ArrayList<Posao> poslovi = formPosao.getPoslovi();
        for (Posao p : poslovi) {
            if (p.equals(selektovaniPosao)) {
                selektovaniPosaoJeUListi = true;
                break;
            }
        }
        if (selektovaniPosaoJeUListi) {
            formPosao.setSelectedPosao(selektovaniPosao);
        } else {
            formPosao.setLastPosao();
        }

        // === ZAPOSLENI ===
        Zaposleni selektovaniZaposleni = formZaposleni.getSelektovaniZaposleni();
        formZaposleni.popuniComboBoxZaposleni();
        boolean selektovaniZaposleniJeUListi = false;
        ArrayList<Zaposleni> zaposleniList = formZaposleni.getZaposleni();
        for (Zaposleni z : zaposleniList) {
            if (z.equals(selektovaniZaposleni)) {
                selektovaniZaposleniJeUListi = true;
                break;
            }
        }
        if (selektovaniZaposleniJeUListi) {
            formZaposleni.setSelectedZaposleni(selektovaniZaposleni);
        } else {
            formZaposleni.setLastZaposleni();
        }

        // === ZADATAK ===
        Zadatak selektovaniZadatak = formZadatak.getSelektovaniZadatak();
        formZadatak.popuniComboBoxZadaci();
        boolean selektovaniZadatakJeUListi = false;
        ArrayList<Zadatak> zadaci = formZadatak.getZadaci();
        for (Zadatak z : zadaci) {
            if (z.equals(selektovaniZadatak)) {
                selektovaniZadatakJeUListi = true;
                break;
            }
        }
        if (selektovaniZadatakJeUListi) {
            formZadatak.setSelectedZadatak(selektovaniZadatak);
        } else {
            formZadatak.setLastZadatak();
        }
    }
}
